development:
  adapter: postgresql
  encoding: unicode
  database: kaizen_development
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: kaizen_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: kaizen_production
  pool: 5
  username: deployer
  password:
